---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insureme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insureme
  template:
    metadata:
      labels:
        app: insureme
    spec:
      containers:
        - name: insurance
          image: muzammilp/insuranceimgaddbook:latest
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
---
apiVersion: v1
kind: Service
metadata:
  name: insureme
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: insureme
